# base image with python
FROM python:3.10-slim

#Install dependiencies (curl for ollama)
RUN apt-get update && apt-get install -y curl && apt-get clean

# Install Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# set working directory
WORKDIR /chatbotapp

# Copy dependencies
COPY requirements.txt .

#Install python deps
RUN pip install --no-cache-dir -r requirements.txt

#Copy project files
COPY ..

#Expose ports
EXPOSE 8000 # FastApi
EXPOSE 11434 # Ollama API

#start Ollama daemon + fast api
CMD ollama serve & uvicorn main:app --host 0.0.0.0 --port 8000

